import type { Metadata } from "next"
import "../styles/globals.css"
import { UserProvider } from "@auth0/nextjs-auth0/client"
import { Abolition, SNPro } from "@/configs/fonts/custom-fonts"
import Header from "@/components/layout/header"
import Footer from "@/components/layout/footer"
import { Toaster } from "@/components/ui/sonner"
import { ThemeProvider } from "@/components/providers/theme-provider"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <UserProvider>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <body
            className={`${Abolition.variable} ${SNPro.variable} flex flex-col min-h-screen`}
          >
            <Header />
            <main className="flex-1 container mx-auto py-8 overflow-auto">
              {children}
            </main>
            <Toaster />
            <Footer />
          </body>
        </ThemeProvider>
      </UserProvider>
    </html>
  )
}
