import type { Metadata } from "next"
import "../styles/globals.css"
import { UserProvider } from "@auth0/nextjs-auth0/client"
import Header from "@/components/layout/header/header"
import Footer from "@/components/layout/footer/footer"
import { Abolition, SNPro } from "@/config/fonts/custom-fonts"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <body
          className={`${Abolition.variable} ${SNPro.variable} flex flex-col min-h-screen`}
        >
          <Header />
          <main className="flex-1 container mx-auto px-4 py-8 overflow-auto">
            {children}
          </main>
          <Footer />
        </body>
      </UserProvider>
    </html>
  )
}
